Fix for https://github.com/contino/terraform-learn/issues/5
cd terraform-learn/gcp/environments/test/compute
terraform plan -var-file=./terraform.tfvars
Gets you this error

Error: module.demo-node.google_compute_instance.demo-node: "boot_disk": required field is not set
Minor update to will fix this gcp/modules/compute/nodes/demo_node/demo_node.tf

  boot_disk {
    initialize_params {
      image = "${var.image}"
    }
  }